In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('weight-height.csv')

In [3]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.replace(to_replace=["Male", "Female"], value=[1,0], inplace=True) #male=1 ' female=0'

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8555 entries, 0 to 8554
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Gender  8555 non-null   int64  
 1   Height  8555 non-null   float64
 2   Weight  8555 non-null   float64
dtypes: float64(2), int64(1)
memory usage: 200.6 KB


In [6]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

# Setp 1-Regression

In [7]:
df.Gender.value_counts()

1    5000
0    3555
Name: Gender, dtype: int64

In [8]:
#Seperate X,y
x = df.drop('Weight', axis=1)
y = df[['Weight']]

In [9]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y, test_size=.3, random_state=5)

In [12]:
xtrain.head()

Gender     Height
6003       0  62.586464
4336       1  68.451084
7822       0  65.371090
510        1  71.580123
3459       1  67.992714

In [13]:
xtrain.count()

Gender    5988
Height    5988
dtype: int64

In [14]:
ytrain.head()

Weight
6003  132.732255
4336  166.832799
7822  136.471256
510   205.347596
3459  167.176045

In [15]:
df.count()

Gender    8555
Height    8555
Weight    8555
dtype: int64

In [16]:
from sklearn.linear_model import LinearRegression

In [17]:
lr = LinearRegression()

In [18]:
lr.fit(xtrain, ytrain)

LinearRegression()

In [19]:
m = lr.coef_  #calculation is slop m
m

array([[19.52571287,  5.99427005]])

In [20]:
c = lr.intercept_  #calculation of c
c

array([-246.29889826])

In [21]:
yp = (19*68.451084)+(5*1)+c  #y=mx+c   prediction
yp

array([1059.27169774])

In [22]:
lr.predict([[0,68.451084]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[164.01538477]])

In [23]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

In [24]:
df['predicted_Weight'] = lr.predict(x)
df.head()

Gender     Height      Weight  predicted_Weight
0       1  73.847017  241.893563        215.885777
1       1  68.781904  162.310473        185.524122
2       1  74.110105  212.740856        217.462800
3       1  71.730978  220.042470        203.201670
4       1  69.881796  206.349801        192.117171

In [25]:
from sklearn.metrics import mean_squared_error, mean_absolute_error

In [26]:
mse = mean_squared_error(ytest, lr.predict(xtest))
mae = mean_absolute_error(ytest, lr.predict(xtest))

In [27]:
mae

8.053184439750341

In [28]:
mse

104.68513633926095

In [29]:
lr.score(xtest, ytest)

0.8951618640664372

In [30]:
lr.score(xtrain, ytrain)

0.9019247421722165

In [31]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error


In [32]:
knn =KNeighborsRegressor(n_neighbors=50)

In [33]:
knn.fit(xtrain,ytrain)

KNeighborsRegressor(n_neighbors=50)

In [34]:
kr = knn.predict(xtest)

In [35]:
mean_squared_error(ytest, kr)

108.14255107602808

In [36]:
kr.score(xtest, ytest)

AttributeError: 'numpy.ndarray' object has no attribute 'score'

# step 2-clAssification

In [ ]:
import pandas as pd
import numpy as np
from sklearn.neighbors import KNeighborsClassifier


In [ ]:
df = pd.read_csv('weight-height.csv')

In [ ]:
df.head()

In [ ]:

df.replace(to_replace=["Male", "Female"], value=[1,0], inplace=True) #male=1 ' female=0'

In [ ]:
df.head()

In [ ]:
x = df.drop('Gender', axis=1)
y = df[['Gender']]

In [ ]:
x.head()

In [ ]:
y.head()

In [ ]:
knn =KNeighborsRegressor(n_neighbors=100)

In [ ]:
knn.fit(xtrain,ytrain)

In [ ]:
y = knn.predict(xtest)

In [ ]:
from sklearn.metrics import confusion_matrix

In [38]:
confusion_matrix(ytest,y)

NameError: name 'confusion_matrix' is not defined